### ISSUE TITLE
Spice up virtual world with more obstacles

### ISSUE THREAD

**Issue by RuthgerD** [ItJustWorksTM/smce-gd#27]
Currently its basically an empty waste land with an epic ramp.
We need some obstacles to exercise the sensors

**Comment by RuthgerD** [comment]
partially fixed with ae6d383

**Comment by RuthgerD** [comment]
obligatory screenshot
![image](https://user-images.githubusercontent.com/57626200/111531172-77b8a100-8764-11eb-87cb-b9d465a331f7.png)

**Comment by RuthgerD** [comment]
@platisd What do you think? the environment is pretty nice and already provides some obstacles and hills but maybe a couple of hard to miss obstacles might be helpful (e.g. a straight up wall in the field or something) any simple geometry is no issue to put in :)

**Comment by platisd** [comment]
@RuthgerD let's have a sync today :bulb: 
17:30 perhaps?

**Comment by AeroStun** [comment]
Sure thing
