### ISSUE TITLE
Do we keep the car?

### ISSUE THREAD

**Issue by RuthgerD** [ItJustWorksTM/smce-gd#33]
Im pretty sure anyone who tried smce-gd has played around with the little physics car I made using the manual control, and we all know how fun that is (especially with our shooty easter egg).
But it really only exists to test the physics and since things have started getting way more usable Im not sure if we want to spawn it by default like we have now because it doesn't really have "official" support.

So the question is, how do we integrate the car without getting in the way of official business.

**Comment by AeroStun** [comment]
My take would be that we should have a global settings menu, where we can choose whether we enable the manual car or not.

**Comment by RuthgerD** [comment]
Bound to a key to spawn for now: 0f1e919
