### ISSUE TITLE
Megaspam of UTF8 decoding errors from Godot on Windows when a sketch is running

### ISSUE THREAD

**Issue by AeroStun** [ItJustWorksTM/smce-gd#38]
`Unicode error (invalid skip)` times infinity

**Comment by RuthgerD** [comment]
Just to be clear, this happens when you try to display invalid utf-8 characters. What introduced this?

**Comment by AeroStun** [comment]
I saw it in action when I tested the new MQTT backend yesterday

**Comment by AeroStun** [comment]
Note that when the sketched is paused, the spam pauses too; might have to do with the UART or log pullers, could need to sanitize them, or tell me what non-UTF character is being refused, so I can track it down the pipes

**Comment by AeroStun** [comment]
Fixed by 4a17bd5753e7a1b9aa8dfe87d536c50eceadb9e2
