### ISSUE TITLE
Odometer unit

### ISSUE THREAD

**Issue by alrapal** [ItJustWorksTM/smce-gd#47]
Hi!
I just would like to bring up to you that the odometers in the emulator are showing the distance in m whereas in the library it is cm.
I don't know if it is a bug or intended, but there is no mention of that change in the documentation. 
I thought it would be nice for you to know that so you could either update the doc or the unit :D 

Have a nice day !

**Comment by AeroStun** [comment]
Our UI intends to show values in SI units. The SmartcarShield API may use different units, but they should still represent the same physical value.

**Comment by AeroStun** [comment]
(Note that the Godot environment is not in a 1:1 scale either; we do compensate.)

**Comment by RuthgerD** [comment]
Like Ryan explained, we use standard units in the UI (since the very beginning) as they are more readable, they still are derived from the exact value you get in arduino land.
I don't believe we have changed anything about that so if you believe it did change (in an incorrect way) let me know.
