### ISSUE TITLE
[Bug] Wheel rotation direction

### ISSUE THREAD

**Issue by axe007** [ItJustWorksTM/smce-gd#48]
Car's wheels turn backwards when going forward and visa versa.

Changing X vector value into negative number, on RayCar.gd Line 76 fixes it:
Previously:
- wheel.get_child(0).rotate(Vector3(1,0,0), _wheels[i].throttle * PI/5)

And changed to:
- wheel.get_child(0).rotate(Vector3(-1,0,0), _wheels[i].throttle * PI/5)

**Comment by RuthgerD** [comment]
As discussed privately, this does not affect the car shipped in master; so it's not a bug.
I will review if we do something odd with the local rotation though.
